language: ruby
sudo: false
cache:
  bundler: true
services: postgresql
addons:
  postgresql: 9.6
script:
  - bundle exec danger
  - bundle exec rake db:create db:schema:load
  - bundle exec rspec
  - bundle exec cucumber
