FROM ministryofjustice/ruby:2.3.1-webapp-onbuild

RUN touch /etc/inittab

RUN apt-get update && apt-get install -y

# Make sure we install development and test gems
# (the FROM Dockerfile sets them as --without options which get cached
# in Bundler configuration)
RUN rm /usr/local/bundle/config
RUN bundle config --delete without
RUN bundle install

CMD bundle exec puma -p $PUMA_PORT
