#!/usr/bin/env ruby

require 'yaml'
require 'pp'

# http://stackoverflow.com/a/30225093/794111
class ::Hash
  def deep_merge(second)
    merger = proc { |_key, v1, v2| Hash === v1 && Hash === v2 ? v1.merge(v2, &merger) : Array === v1 && Array === v2 ? v1 | v2 : [:undefined, nil, :nil].include?(v2) ? v1 : v2 }
    self.merge(second.to_h, &merger)
  end
end

def merge_yaml(hash, file)
  hash.deep_merge(YAML.load(File.read(file)))
end

############################################################

hash = {}

ARGV.each do |file|
  hash = merge_yaml(hash, file)
end

puts YAML.dump(hash)

