Rails.application.config.filter_parameters += [
  :closure_additional_information,
  :comment,
  :confirmation_code,
  :grounds_for_appeal,
  :hardship_reason,
  :having_problems_uploading_explanation,
  :lateness_reason,
  :outcome,
  :password,
  :representative_contact_address,
  :representative_contact_email,
  :representative_contact_phone,
  :representative_contact_postcode,
  :taxpayer_contact_address,
  :taxpayer_contact_email,
  :taxpayer_contact_phone,
  :taxpayer_contact_postcode
]
