 # This file is only present to fix a Jenkins
# build error that started to occur after
# adding devise, but which we could not
# reproduce on our local machines
default: &default
  adapter: postgresql
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: '<%= ENV["DB_PASSWORD"] %>'
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>

development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'tt-datacapture_development') %>
test: &test
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'tt-datacapture_test') %><%= ENV['TEST_ENV_NUMBER'] %>
production:
  <<: *default

cucumber:
  <<: *test
