default:
  adapter: postgresql
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: '<%= ENV["DB_PASSWORD"] %>'
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>

development:
  adapter: postgresql
  database: <%= ENV.fetch('DB_NAME', 'tt-datacapture_development') %>
  username: <%= ENV["DB_USERNAME"] %>
  password: '<%= ENV["DB_PASSWORD"] %>'
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>

test:
  adapter: postgresql
  database: <%= ENV.fetch('DB_NAME', 'tt-datacapture_test') %><%= ENV['TEST_ENV_NUMBER'] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: '<%= ENV["DB_PASSWORD"] %>'
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>

production:
  adapter: postgresql
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: '<%= ENV["DB_PASSWORD"] %>'
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  sslmode: 'require'

cucumber:
  adapter: postgresql
  database: <%= ENV.fetch('DB_NAME', 'tt-datacapture_test') %><%= ENV['TEST_ENV_NUMBER'] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: '<%= ENV["DB_PASSWORD"] %>'
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
