parameters:
  rubyVersion: ''
  bundlerVersion: ''


steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '$(rubyVersion)'

- script: |
    gem install bundler -v $(bundlerVersion)
  displayName: 'install bundler'

- script: |
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: |
    psql -h localhost -c 'create role vsts login createdb superuser;' -U postgres
  displayName: 'PG role setup'

- script: |
    env
  displayName: 'env list'

- script: |
    bundle exec rake db:create
  displayName: 'DB create'

- script: |
    bundle exec rake db:schema:load
  displayName: 'DB load'

- script: |
    CAPYBARA_SERVER_PORT=random bundle exec cucumber
  displayName: 'cucumber'
