parameters:
  rubyVersion: ''
  bundlerVersion: ''


steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '$(rubyVersion)'

- script: |
    gem install bundler -v $(bundlerVersion)
  displayName: 'install bundler'

- script: |
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    bundle exec rubocop --fail-fast
  displayName: 'rubocop'

- script: |
    psql -h localhost -c 'create role vsts login createdb superuser;' -U postgres
  displayName: 'PG role setup'

- script: |
    bundle exec rake db:create db:schema:load
  displayName: 'creade DB'

- script: |
    bundle exec rspec --fail-fast --format documentation --format RspecJunitFormatter --out test-rspec.xml
  displayName: 'test rspec'

- script: |
    bundle exec cucumber --fail-fast
  displayName: 'test cucumber'

- script: |
    bundle exec rails s -p 3000 & sleep 5; npm run pa11y-ci
  displayName: 'run pa11y'

- script: |
    bundle exec brakeman
  displayName: 'brakeman'
