parameters:
  rubyVersion: ''
  bundlerVersion: ''

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '$(rubyVersion)'

- script: |
    gem install bundler -v $(bundlerVersion)
  displayName: 'install bundler'

- task: Cache@2
  inputs:
    key: 'gems | "$(Agent.OS)" | Gemfile.lock'
    restoreKeys: |
      gems | "$(Agent.OS)"
      gems
    path: $(BUNDLE_PATH)
    cacheHitVar: GEM_CACHE_RESTORED
  displayName: 'Cache gems'

- script: |
    bundle install --retry=3 --jobs=4
  condition: ne(variables.GEM_CACHE_RESTORED, 'true')
  displayName: 'bundle install'

- script: |
    npm install --production
  displayName: 'npm install'

- script: |
    bundle exec rubocop --fail-fast
  displayName: 'rubocop'

- script: |
    psql -h localhost -c 'create role vsts login createdb superuser;' -U postgres
  displayName: 'PG role setup'

- script: |
    bundle exec rake db:create db:schema:load
  displayName: 'create DB'

- script: |
    bundle exec rspec --fail-fast --format documentation --format RspecJunitFormatter --out test-rspec.xml
  displayName: 'test rspec'

- script: |
    echo 'bundle exec cucumber --fail-fast'
  displayName: 'test cucumber'

- script: |
    bundle exec brakeman
  displayName: 'brakeman'